kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: "puisi-ingress"
  namespace: belajar-namespace
spec:
  rules:
    - host: web-puisi.10.18.5.2.xip.io
      http:
        paths:
          - path: /
            backend:
              serviceName: puisi-service
              servicePort: 80