apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-puisi
spec:
  selector:
    matchLabels:
      app: web-puisi
      tier: web
  replicas: 1
  template:
    metadata:
      labels:
        app: web-puisi
        tier: web
    spec:
      containers:
      - name: web-puisi
        image: asia.gcr.io/rizky-belajar/web-puisi:1.0.1
        resources: {}
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: rizkyreg